version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: leadpilot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: leadpilot
    ports:
      - "5433:5432"
    volumes:
      # 这里换了一块名叫 v2 的全新硬盘
      - postgres_data_v2:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: leadpilot_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data_v2:
  redis_data: